///////////////////////////////////////////////////////////
//  Fomrularz_WprowadüDaneOsobowe.cs
//  Implementation of the Class Fomrularz_WprowadüDaneOsobowe
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:52
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Wprowadü wymagane dane osobowe.
/// </summary>
public class Fomrularz_WprowadüDaneOsobowe {

	private string contact;
	private string name;

	public Fomrularz_WprowadüDaneOsobowe(){

	}

	~Fomrularz_WprowadüDaneOsobowe(){

	}

	public Ster_WprowadüDaneOsobowe Ster_WprowadüDaneOsobowe{
		get{
			return m_Ster_WprowadüDaneOsobowe;
		}
		set{
			m_Ster_WprowadüDaneOsobowe = value;
		}
	}

	public void wprowadzDane(){

	}

}//end Fomrularz_WprowadüDaneOsobowe