///////////////////////////////////////////////////////////
//  Formularz_GerenujRaport.cs
//  Implementation of the Class Formularz_GerenujRaport
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:14
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_GerenujRaport {

	public Formularz_GerenujRaport(){

	}

	~Formularz_GerenujRaport(){

	}

	public Ster_GerenujRaport Ster_GerenujRaport{
		get{
			return m_Ster_GerenujRaport;
		}
		set{
			m_Ster_GerenujRaport = value;
		}
	}

}//end Formularz_GerenujRaport