///////////////////////////////////////////////////////////
//  Formularz_WybierzSale.cs
//  Implementation of the Class Formularz_WybierzSale
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:53
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_WybierzSale {

	private Dane.Sala sala;

	public Formularz_WybierzSale(){

	}

	~Formularz_WybierzSale(){

	}

	public Ster_WybierzSale Ster_WybierzSale{
		get{
			return m_Ster_WybierzSale;
		}
		set{
			m_Ster_WybierzSale = value;
		}
	}

}//end Formularz_WybierzSale