///////////////////////////////////////////////////////////
//  Formularz_AnulujRezerwacjê.cs
//  Implementation of the Class Formularz_AnulujRezerwacjê
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:47
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_AnulujRezerwacjê {

	private Dane.Status status;

	public Formularz_AnulujRezerwacjê(){

	}

	~Formularz_AnulujRezerwacjê(){

	}

	public Ster_AnulujRezerwacjê Ster_AnulujRezerwacjê{
		get{
			return m_Ster_AnulujRezerwacjê;
		}
		set{
			m_Ster_AnulujRezerwacjê = value;
		}
	}

	public Ster_Odœwie¿Stoliki Ster_Odœwie¿Stoliki{
		get{
			return m_Ster_Odœwie¿Stoliki;
		}
		set{
			m_Ster_Odœwie¿Stoliki = value;
		}
	}

}//end Formularz_AnulujRezerwacjê