///////////////////////////////////////////////////////////
//  Formularz_Zarz¹dzajRezerwacja.cs
//  Implementation of the Class Formularz_Zarz¹dzajRezerwacja
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:59
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_Zarz¹dzajRezerwacja {

	private char Treœæ anuluj rezerwacje;
	private char Treœæ utwórz rezerwacjê;

	public Formularz_Zarz¹dzajRezerwacja(){

	}

	~Formularz_Zarz¹dzajRezerwacja(){

	}

	public Ster_Zarz¹dzajRezerwacj¹ Ster_Zarz¹dzajRezerwacj¹{
		get{
			return m_Ster_Zarz¹dzajRezerwacj¹;
		}
		set{
			m_Ster_Zarz¹dzajRezerwacj¹ = value;
		}
	}

	public void zarz¹dzajK(){

	}

}//end Formularz_Zarz¹dzajRezerwacja