///////////////////////////////////////////////////////////
//  Formularz_WyœlijPowiadomienie.cs
//  Implementation of the Class Formularz_WyœlijPowiadomienie
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:56
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_WyœlijPowiadomienie {

	private int trescPowiadomienia;

	public Formularz_WyœlijPowiadomienie(){

	}

	~Formularz_WyœlijPowiadomienie(){

	}

	public Ster_WyœlijPowiadomienie Ster_WyœlijPowiadomienie{
		get{
			return m_Ster_WyœlijPowiadomienie;
		}
		set{
			m_Ster_WyœlijPowiadomienie = value;
		}
	}

}//end Formularz_WyœlijPowiadomienie