///////////////////////////////////////////////////////////
//  FormularzK_ZmienDane.cs
//  Implementation of the Class FormularzK_ZmienDane
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:59
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzK_ZmienDane {

	private string name;

	public FormularzK_ZmienDane(){

	}

	~FormularzK_ZmienDane(){

	}

	public Ster_ZmienDane Ster_ZmienDane{
		get{
			return m_Ster_ZmienDane;
		}
		set{
			m_Ster_ZmienDane = value;
		}
	}

	public void zmienDane(){

	}

}//end FormularzK_ZmienDane