///////////////////////////////////////////////////////////
//  Formularz_AnalizujStatystykiRezerwacji.cs
//  Implementation of the Class Formularz_AnalizujStatystykiRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:10
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_AnalizujStatystykiRezerwacji {

	public Formularz_AnalizujStatystykiRezerwacji(){

	}

	~Formularz_AnalizujStatystykiRezerwacji(){

	}

	public Ster_AnalizujStatystykiRezerwacji Ster_AnalizujStatystykiRezerwacji{
		get{
			return m_Ster_AnalizujStatystykiRezerwacji;
		}
		set{
			m_Ster_AnalizujStatystykiRezerwacji = value;
		}
	}

}//end Formularz_AnalizujStatystykiRezerwacji