///////////////////////////////////////////////////////////
//  Formularz_UsuñStolik.cs
//  Implementation of the Class Formularz_UsuñStolik
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:27
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_UsuñStolik {

	private int idStolik;

	public Formularz_UsuñStolik(){

	}

	~Formularz_UsuñStolik(){

	}

	public Ster_UsuñStolik Ster_UsuñStolik{
		get{
			return m_Ster_UsuñStolik;
		}
		set{
			m_Ster_UsuñStolik = value;
		}
	}

	public void usuñStolik(){

	}

}//end Formularz_UsuñStolik