///////////////////////////////////////////////////////////
//  FormularzK_Zarz퉐zajKontem.cs
//  Implementation of the Class FormularzK_Zarz퉐zajKontem
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:57
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzK_Zarz퉐zajKontem {

	public FormularzK_Zarz퉐zajKontem(){

	}

	~FormularzK_Zarz퉐zajKontem(){

	}

	public Ster_Zarz퉐zajKontem Ster_Zarz퉐zajKontem{
		get{
			return m_Ster_Zarz퉐zajKontem;
		}
		set{
			m_Ster_Zarz퉐zajKontem = value;
		}
	}

}//end FormularzK_Zarz퉐zajKontem