///////////////////////////////////////////////////////////
//  FormularzP_ZmienStatusRezerwacji.cs
//  Implementation of the Class FormularzP_ZmienStatusRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:01
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class FormularzP_ZmienStatusRezerwacji {

	private Dane.Status Status;

	public FormularzP_ZmienStatusRezerwacji(){

	}

	~FormularzP_ZmienStatusRezerwacji(){

	}

	public Ster_ZmienStatsuRezerwacji Ster_ZmienStatsuRezerwacji{
		get{
			return m_Ster_ZmienStatsuRezerwacji;
		}
		set{
			m_Ster_ZmienStatsuRezerwacji = value;
		}
	}

}//end FormularzP_ZmienStatusRezerwacji