///////////////////////////////////////////////////////////
//  FormularzP_ZmieñUprawnienia.cs
//  Implementation of the Class FormularzP_ZmieñUprawnienia
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:11:00
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzP_ZmieñUprawnienia {

	private int idUprawnienia;

	public FormularzP_ZmieñUprawnienia(){

	}

	~FormularzP_ZmieñUprawnienia(){

	}

	public Ster_ZmieñUprawnienia Ster_ZmieñUprawnienia{
		get{
			return m_Ster_ZmieñUprawnienia;
		}
		set{
			m_Ster_ZmieñUprawnienia = value;
		}
	}

}//end FormularzP_ZmieñUprawnienia