///////////////////////////////////////////////////////////
//  Formularz_Odœwie¿Stoliki.cs
//  Implementation of the Class Formularz_Odœwie¿Stoliki
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:49
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_Odœwie¿Stoliki {

	private Dane.Sala sala;

	public Formularz_Odœwie¿Stoliki(){

	}

	~Formularz_Odœwie¿Stoliki(){

	}

}//end Formularz_Odœwie¿Stoliki