///////////////////////////////////////////////////////////
//  Formularz_DodajSale.cs
//  Implementation of the Class Formularz_DodajSale
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:22
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_DodajSale {

	private Dane.Sala Sala;

	public Formularz_DodajSale(){

	}

	~Formularz_DodajSale(){

	}

	public void dodaj salê(){

	}

	public Ster_DodajSale Ster_DodajSale{
		get{
			return m_Ster_DodajSale;
		}
		set{
			m_Ster_DodajSale = value;
		}
	}

}//end Formularz_DodajSale