///////////////////////////////////////////////////////////
//  FormularzP_Zarz¹dzajSalami.cs
//  Implementation of the Class FormularzP_Zarz¹dzajSalami
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:35
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzP_Zarz¹dzajSalami {

	private char Treœæ iloœæ stolików;
	private char Treœæ roz³o¿enie stolików;
	private char Treœæ typ sali;

	public FormularzP_Zarz¹dzajSalami(){

	}

	~FormularzP_Zarz¹dzajSalami(){

	}

	public Ster_Zarz¹dzajSalami Ster_Zarz¹dzajSalami{
		get{
			return m_Ster_Zarz¹dzajSalami;
		}
		set{
			m_Ster_Zarz¹dzajSalami = value;
		}
	}

}//end FormularzP_Zarz¹dzajSalami