///////////////////////////////////////////////////////////
//  Formularz_Przegl¹dajHistoriêRezerwacji.cs
//  Implementation of the Class Formularz_Przegl¹dajHistoriêRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:54
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_Przegl¹dajHistoriêRezerwacji {

	private int idUser;

	public Formularz_Przegl¹dajHistoriêRezerwacji(){

	}

	~Formularz_Przegl¹dajHistoriêRezerwacji(){

	}

	public Ster_Przegl¹dajHistoriêRezerwacji Ster_Przegl¹dajHistoriêRezerwacji{
		get{
			return m_Ster_Przegl¹dajHistoriêRezerwacji;
		}
		set{
			m_Ster_Przegl¹dajHistoriêRezerwacji = value;
		}
	}

}//end Formularz_Przegl¹dajHistoriêRezerwacji