///////////////////////////////////////////////////////////
//  Formularz_Zarz퉐zajStolikamiWSali.cs
//  Implementation of the Class Formularz_Zarz퉐zajStolikamiWSali
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:28
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_Zarz퉐zajStolikamiWSali {

	private Dane.Stolik Stolik;

	public Formularz_Zarz퉐zajStolikamiWSali(){

	}

	~Formularz_Zarz퉐zajStolikamiWSali(){

	}

	public Ster_Zarz퉐zajStolikamiWSali Ster_Zarz퉐zajStolikamiWSali{
		get{
			return m_Ster_Zarz퉐zajStolikamiWSali;
		}
		set{
			m_Ster_Zarz퉐zajStolikamiWSali = value;
		}
	}

}//end Formularz_Zarz퉐zajStolikamiWSali