///////////////////////////////////////////////////////////
//  Formularz_AnalizujDane.cs
//  Implementation of the Class Formularz_AnalizujDane
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:09
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_AnalizujDane {

	private char Treœæ podgl¹daj dane;
	private char Treœæ wybierz dane;

	public Formularz_AnalizujDane(){

	}

	~Formularz_AnalizujDane(){

	}

	public void generujRaportP(){

	}

	public Ster_AnalizujDane Ster_AnalizujDane{
		get{
			return m_Ster_AnalizujDane;
		}
		set{
			m_Ster_AnalizujDane = value;
		}
	}

}//end Formularz_AnalizujDane