///////////////////////////////////////////////////////////
//  Formularz_ZmieñTypSali.cs
//  Implementation of the Class Formularz_ZmieñTypSali
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:30
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_ZmieñTypSali {

	private int idSala;
	private int typ;

	public Formularz_ZmieñTypSali(){

	}

	~Formularz_ZmieñTypSali(){

	}

	public Ster_ZmieñTypSali Ster_ZmieñTypSali{
		get{
			return m_Ster_ZmieñTypSali;
		}
		set{
			m_Ster_ZmieñTypSali = value;
		}
	}

}//end Formularz_ZmieñTypSali