///////////////////////////////////////////////////////////
//  Formularz_UtwórzRezerwacje.cs
//  Implementation of the Class Formularz_UtwórzRezerwacje
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:51
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_UtwórzRezerwacje {

	private Dane.Klient Klient;

	public Formularz_UtwórzRezerwacje(){

	}

	~Formularz_UtwórzRezerwacje(){

	}

	public Ster_UtwórzRezerwacje Ster_UtwórzRezerwacje{
		get{
			return m_Ster_UtwórzRezerwacje;
		}
		set{
			m_Ster_UtwórzRezerwacje = value;
		}
	}

	public void utwórzRezerwacjeK(){

	}

}//end Formularz_UtwórzRezerwacje