///////////////////////////////////////////////////////////
//  Formularz_EksportujRaport.cs
//  Implementation of the Class Formularz_EksportujRaport
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:12
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_EksportujRaport {

	public Formularz_EksportujRaport(){

	}

	~Formularz_EksportujRaport(){

	}

	public Ster_EksportujRaport Ster_EksportujRaport{
		get{
			return m_Ster_EksportujRaport;
		}
		set{
			m_Ster_EksportujRaport = value;
		}
	}

}//end Formularz_EksportujRaport