///////////////////////////////////////////////////////////
//  Formularz_ZweryfikujDaneSali.cs
//  Implementation of the Class Formularz_ZweryfikujDaneSali
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:33
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_ZweryfikujDaneSali {

	private int idSala;

	public Formularz_ZweryfikujDaneSali(){

	}

	~Formularz_ZweryfikujDaneSali(){

	}

	public Ster_ZweryfikujDaneSali Ster_ZweryfikujDaneSali{
		get{
			return m_Ster_ZweryfikujDaneSali;
		}
		set{
			m_Ster_ZweryfikujDaneSali = value;
		}
	}

	public void weryfikacja(){

	}

}//end Formularz_ZweryfikujDaneSali