///////////////////////////////////////////////////////////
//  Formularz_WybierzStolik.cs
//  Implementation of the Class Formularz_WybierzStolik
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:55
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_WybierzStolik {

	private Dane.Stolik stolik;

	public Formularz_WybierzStolik(){

	}

	~Formularz_WybierzStolik(){

	}

	public Ster_WybierzStolik Ster_WybierzStolik{
		get{
			return m_Ster_WybierzStolik;
		}
		set{
			m_Ster_WybierzStolik = value;
		}
	}

}//end Formularz_WybierzStolik