///////////////////////////////////////////////////////////
//  Formularz_WybierzTermin.cs
//  Implementation of the Class Formularz_WybierzTermin
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:56
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_WybierzTermin {

	private Dane.Termin Termin;

	public Formularz_WybierzTermin(){

	}

	~Formularz_WybierzTermin(){

	}

	public WybierzTermin WybierzTermin{
		get{
			return m_WybierzTermin;
		}
		set{
			m_WybierzTermin = value;
		}
	}

}//end Formularz_WybierzTermin