///////////////////////////////////////////////////////////
//  Formularz_UsuñSalê.cs
//  Implementation of the Class Formularz_UsuñSalê
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:25
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_UsuñSalê {

	private int idSala;

	public Formularz_UsuñSalê(){

	}

	~Formularz_UsuñSalê(){

	}

	public Ster_UsuñSalê Ster_UsuñSalê{
		get{
			return m_Ster_UsuñSalê;
		}
		set{
			m_Ster_UsuñSalê = value;
		}
	}

	public void usuñSalê(){

	}

}//end Formularz_UsuñSalê