///////////////////////////////////////////////////////////
//  Formularz_WyslijPowiadomienieOStanieRezerwacji.cs
//  Implementation of the Class Formularz_WyslijPowiadomienieOStanieRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:58
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_WyslijPowiadomienieOStanieRezerwacji {

	private char Treœæ wyœlij powiadomienie o stanie rezerwacji;

	public Formularz_WyslijPowiadomienieOStanieRezerwacji(){

	}

	~Formularz_WyslijPowiadomienieOStanieRezerwacji(){

	}

	public Ster_WyslijPowiadomieOStanieRezerwacji Ster_WyslijPowiadomieOStanieRezerwacji{
		get{
			return m_Ster_WyslijPowiadomieOStanieRezerwacji;
		}
		set{
			m_Ster_WyslijPowiadomieOStanieRezerwacji = value;
		}
	}

}//end Formularz_WyslijPowiadomienieOStanieRezerwacji