///////////////////////////////////////////////////////////
//  Formularz_WybierzOkazje.cs
//  Implementation of the Class Formularz_WybierzOkazje
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:09:52
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_WybierzOkazje {

	private Dane.Okazja Okazja;

	public Formularz_WybierzOkazje(){

	}

	~Formularz_WybierzOkazje(){

	}

	public Ster_WybierzOkazje Ster_WybierzOkazje{
		get{
			return m_Ster_WybierzOkazje;
		}
		set{
			m_Ster_WybierzOkazje = value;
		}
	}

}//end Formularz_WybierzOkazje