///////////////////////////////////////////////////////////
//  Formularz_DodajStolik.cs
//  Implementation of the Class Formularz_DodajStolik
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:24
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Formularz_DodajStolik {

	private int Liczbaosob;
	private int Miejsce;
	private sbyte Sala;

	public Formularz_DodajStolik(){

	}

	~Formularz_DodajStolik(){

	}

	public void dodajStolik(){

	}

	public Ster_DodajStolik Ster_DodajStolik{
		get{
			return m_Ster_DodajStolik;
		}
		set{
			m_Ster_DodajStolik = value;
		}
	}

}//end Formularz_DodajStolik