///////////////////////////////////////////////////////////
//  Formularz_UtwórzKonto.cs
//  Implementation of the Class Formularz_UtwórzKonto
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:10:55
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Formularz_UtwórzKonto {

	private int idUser;
	private string name;
	private Dane.uprawnienia uprawnienia;

	public Formularz_UtwórzKonto(){

	}

	~Formularz_UtwórzKonto(){

	}

	public Ster_UtwórzKonto Ster_UtwórzKonto{
		get{
			return m_Ster_UtwórzKonto;
		}
		set{
			m_Ster_UtwórzKonto = value;
		}
	}

}//end Formularz_UtwórzKonto