///////////////////////////////////////////////////////////
//  Ster_Zarz¹dzajRezerwacj¹.cs
//  Implementation of the Class Ster_Zarz¹dzajRezerwacj¹
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:14
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_Zarz¹dzajRezerwacj¹ {

	private char Treœæ anuluj rezerwacjê;
	private char Treœæ utwórz rezerwacjê;
	private Dane.Osoba U¿ytkownik;

	public Ster_Zarz¹dzajRezerwacj¹(){

	}

	~Ster_Zarz¹dzajRezerwacj¹(){

	}

	public void pobierzOpcje()(){

	}

	public Rezerwacja Rezerwacja{
		get{
			return m_Rezerwacja;
		}
		set{
			m_Rezerwacja = value;
		}
	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

}//end Ster_Zarz¹dzajRezerwacj¹