///////////////////////////////////////////////////////////
//  Ster_ZmieñTypSali.cs
//  Implementation of the Class Ster_ZmieñTypSali
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:48
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_ZmieñTypSali {

	public Ster_ZmieñTypSali(){

	}

	~Ster_ZmieñTypSali(){

	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

	public void zmienTyp(){

	}

}//end Ster_ZmieñTypSali