///////////////////////////////////////////////////////////
//  Ster_GerenujRaport.cs
//  Implementation of the Class Ster_GerenujRaport
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:11:45
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_GerenujRaport {

	private Dane.Statystki statystyki;

	public Ster_GerenujRaport(){

	}

	~Ster_GerenujRaport(){

	}

	public Dane Dane{
		get{
			return m_Dane;
		}
		set{
			m_Dane = value;
		}
	}

	public void generujRaport(){

	}

}//end Ster_GerenujRaport