///////////////////////////////////////////////////////////
//  Ster_UtwórzKonto.cs
//  Implementation of the Class Ster_UtwórzKonto
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:13:39
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_UtwórzKonto {

	public Ster_UtwórzKonto(){

	}

	~Ster_UtwórzKonto(){

	}

	public void utwórzKonto(){

	}

	public Uzytkownik Uzytkownik{
		get{
			return m_Uzytkownik;
		}
		set{
			m_Uzytkownik = value;
		}
	}

}//end Ster_UtwórzKonto