///////////////////////////////////////////////////////////
//  Ster_AnalizujDane.cs
//  Implementation of the Class Ster_AnalizujDane
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:11:41
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_AnalizujDane {

	private char Treœæ podgl¹daj dane;
	private char Treœæ wybierz dane;

	public Ster_AnalizujDane(){

	}

	~Ster_AnalizujDane(){

	}

	public Dane Dane{
		get{
			return m_Dane;
		}
		set{
			m_Dane = value;
		}
	}

	public void pobierzDane(){

	}

}//end Ster_AnalizujDane