///////////////////////////////////////////////////////////
//  Ster_ZmienDane.cs
//  Implementation of the Class Ster_ZmienDane
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:13:43
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZmienDane {

	public Ster_ZmienDane(){

	}

	~Ster_ZmienDane(){

	}

	public Dane u퓓tkownika Dane u퓓tkownika{
		get{
			return m_Dane u퓓tkownika;
		}
		set{
			m_Dane u퓓tkownika = value;
		}
	}

	public void pobierzDane(){

	}

	public void zmienDane(){

	}

}//end Ster_ZmienDane