///////////////////////////////////////////////////////////
//  Ster_UsuñStolik.cs
//  Implementation of the Class Ster_UsuñStolik
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:43
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_UsuñStolik {

	public Ster_UsuñStolik(){

	}

	~Ster_UsuñStolik(){

	}

	public void pobierzStolik(){

	}

	public Stolik Stolik{
		get{
			return m_Stolik;
		}
		set{
			m_Stolik = value;
		}
	}

	public void usunStolik(){

	}

}//end Ster_UsuñStolik