///////////////////////////////////////////////////////////
//  Ster_DodajStolik.cs
//  Implementation of the Class Ster_DodajStolik
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:40
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_DodajStolik {

	public Ster_DodajStolik(){

	}

	~Ster_DodajStolik(){

	}

	public void dodajStolik(){

	}

	public void pobierzStolik(){

	}

	public Stolik Stolik{
		get{
			return m_Stolik;
		}
		set{
			m_Stolik = value;
		}
	}

}//end Ster_DodajStolik