///////////////////////////////////////////////////////////
//  Ster_Odœwie¿Stoliki.cs
//  Implementation of the Class Ster_Odœwie¿Stoliki
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:06
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_Odœwie¿Stoliki {

	private Dane.Sala sala;

	public Ster_Odœwie¿Stoliki(){

	}

	~Ster_Odœwie¿Stoliki(){

	}

	public void odwiezStoliki(){

	}

	public Sala Sala{
		get{
			return sala;
		}
		set{
			sala = value;
		}
	}

}//end Ster_Odœwie¿Stoliki