///////////////////////////////////////////////////////////
//  Ster_DodajSale.cs
//  Implementation of the Class Ster_DodajSale
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:39
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_DodajSale {

	public Ster_DodajSale(){

	}

	~Ster_DodajSale(){

	}

	public void dodajSale(){

	}

	public void pobierzSale(){

	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

}//end Ster_DodajSale