///////////////////////////////////////////////////////////
//  Ster_ZweryfikujDaneSali.cs
//  Implementation of the Class Ster_ZweryfikujDaneSali
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:49
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_ZweryfikujDaneSali {

	public Ster_ZweryfikujDaneSali(){

	}

	~Ster_ZweryfikujDaneSali(){

	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

	public void sprawdzDane(){

	}

}//end Ster_ZweryfikujDaneSali