///////////////////////////////////////////////////////////
//  Ster_WyslijPowiadomieOStanieRezerwacji.cs
//  Implementation of the Class Ster_WyslijPowiadomieOStanieRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:13
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_WyslijPowiadomieOStanieRezerwacji {

	private char Treœæ wyœlij powiadomienie o stanie rezerwacji;

	public Ster_WyslijPowiadomieOStanieRezerwacji(){

	}

	~Ster_WyslijPowiadomieOStanieRezerwacji(){

	}

	public Powiadomienie Powiadomienie{
		get{
			return m_Powiadomienie;
		}
		set{
			m_Powiadomienie = value;
		}
	}

	public void wyslijPowiadomienie(){

	}

}//end Ster_WyslijPowiadomieOStanieRezerwacji