///////////////////////////////////////////////////////////
//  Ster_AnalizujStatystykiRezerwacji.cs
//  Implementation of the Class Ster_AnalizujStatystykiRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:11:42
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_AnalizujStatystykiRezerwacji {

	private AnalizaDanych wybierz dane;

	public Ster_AnalizujStatystykiRezerwacji(){

	}

	~Ster_AnalizujStatystykiRezerwacji(){

	}

	public Dane.Statystki przetwarzajDane(){

		return null;
	}

	public Statystyki Statystyki{
		get{
			return m_Statystyki;
		}
		set{
			m_Statystyki = value;
		}
	}

}//end Ster_AnalizujStatystykiRezerwacji