///////////////////////////////////////////////////////////
//  Ster_AnulujRezerwacjê.cs
//  Implementation of the Class Ster_AnulujRezerwacjê
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:05
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_AnulujRezerwacjê {

	private Dane.Status status;

	public Ster_AnulujRezerwacjê(){

	}

	~Ster_AnulujRezerwacjê(){

	}

	public Status Status{
		get{
			return status;
		}
		set{
			status = value;
		}
	}

	public void zmienStatus(){

	}

}//end Ster_AnulujRezerwacjê