///////////////////////////////////////////////////////////
//  Ster_Przegl¹dajHistoriêRezerwacji.cs
//  Implementation of the Class Ster_Przegl¹dajHistoriêRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:13:38
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Przegl¹dajHistoriêRezerwacji {

	public Ster_Przegl¹dajHistoriêRezerwacji(){

	}

	~Ster_Przegl¹dajHistoriêRezerwacji(){

	}

	public void getHistory(){

	}

	public Historia rezerwacji Historia rezerwacji{
		get{
			return m_Historia rezerwacji;
		}
		set{
			m_Historia rezerwacji = value;
		}
	}

}//end Ster_Przegl¹dajHistoriêRezerwacji