///////////////////////////////////////////////////////////
//  Ster_WybierzStolik.cs
//  Implementation of the Class Ster_WybierzStolik
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:12
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_WybierzStolik {

	private Dane.Stolik stolik;

	public Ster_WybierzStolik(){

	}

	~Ster_WybierzStolik(){

	}

	public Stolik Stolik{
		get{
			return stolik;
		}
		set{
			stolik = value;
		}
	}

	public void wybierzStolik(){

	}

}//end Ster_WybierzStolik