///////////////////////////////////////////////////////////
//  Ster_UsuñSalê.cs
//  Implementation of the Class Ster_UsuñSalê
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:42
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_UsuñSalê {

	public Ster_UsuñSalê(){

	}

	~Ster_UsuñSalê(){

	}

	public void pobierzSale(){

	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

	public void usunSale(){

	}

}//end Ster_UsuñSalê