///////////////////////////////////////////////////////////
//  Ster_ZmienStatsuRezerwacji.cs
//  Implementation of the Class Ster_ZmienStatsuRezerwacji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:16
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_ZmienStatsuRezerwacji {

	private Dane.Status Wybierz status;

	public Ster_ZmienStatsuRezerwacji(){

	}

	~Ster_ZmienStatsuRezerwacji(){

	}

	public Status Status{
		get{
			return m_Status;
		}
		set{
			m_Status = value;
		}
	}

	public void zmienStatus(){

	}

}//end Ster_ZmienStatsuRezerwacji