///////////////////////////////////////////////////////////
//  Ster_Zarz퉐zajStolikamiWSali.cs
//  Implementation of the Class Ster_Zarz퉐zajStolikamiWSali
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:46
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_Zarz퉐zajStolikamiWSali {

	public Ster_Zarz퉐zajStolikamiWSali(){

	}

	~Ster_Zarz퉐zajStolikamiWSali(){

	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

	public void zmienStoliki(){

	}

}//end Ster_Zarz퉐zajStolikamiWSali