///////////////////////////////////////////////////////////
//  Ster_Zarz¹dzajSalami.cs
//  Implementation of the Class Ster_Zarz¹dzajSalami
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:45
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_Zarz¹dzajSalami {

	private char Treœæ iloœæ stolików;
	private char Treœæ roz³o¿enie stolików;
	private char Treœæ typ sali;

	public Ster_Zarz¹dzajSalami(){

	}

	~Ster_Zarz¹dzajSalami(){

	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

	public Stolik Stolik{
		get{
			return m_Stolik;
		}
		set{
			m_Stolik = value;
		}
	}

}//end Ster_Zarz¹dzajSalami