///////////////////////////////////////////////////////////
//  Ster_WprowadüDaneOsobowe.cs
//  Implementation of the Class Ster_WprowadüDaneOsobowe
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:13:36
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Wprowadü wymagane dane osobowe.
/// </summary>
public class Ster_WprowadüDaneOsobowe {

	public Ster_WprowadüDaneOsobowe(){

	}

	~Ster_WprowadüDaneOsobowe(){

	}

	public Dane uøytkownika Dane uøytkownika{
		get{
			return m_Dane uøytkownika;
		}
		set{
			m_Dane uøytkownika = value;
		}
	}

	public void pobierzDane(){

	}

	public void wprowadzDane(){

	}

}//end Ster_WprowadüDaneOsobowe