///////////////////////////////////////////////////////////
//  Ster_UtwórzRezerwacje.cs
//  Implementation of the Class Ster_UtwórzRezerwacje
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:08
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_UtwórzRezerwacje {

	private char Treœæ wybierz salê i stolik;
	private char Treœæ wybierz termin;

	public Ster_UtwórzRezerwacje(){

	}

	~Ster_UtwórzRezerwacje(){

	}

	public void pobierzOdœwie¿oneDane(){

	}

	public Sala Sala{
		get{
			return m_Sala;
		}
		set{
			m_Sala = value;
		}
	}

}//end Ster_UtwórzRezerwacje