///////////////////////////////////////////////////////////
//  Ster_WyœlijPowiadomienie.cs
//  Implementation of the Class Ster_WyœlijPowiadomienie
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:13:40
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_WyœlijPowiadomienie {

	public Ster_WyœlijPowiadomienie(){

	}

	~Ster_WyœlijPowiadomienie(){

	}

	public Powiadomienie Powiadomienie{
		get{
			return m_Powiadomienie;
		}
		set{
			m_Powiadomienie = value;
		}
	}

	public void wyslijPowiadomienie(){

	}

}//end Ster_WyœlijPowiadomienie