///////////////////////////////////////////////////////////
//  Ster_ZmieñUprawnienia.cs
//  Implementation of the Class Ster_ZmieñUprawnienia
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:13:44
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_ZmieñUprawnienia {

	private char Treœæ uprawnienia;

	public Ster_ZmieñUprawnienia(){

	}

	~Ster_ZmieñUprawnienia(){

	}

	public uprawnienia uprawnienia{
		get{
			return m_uprawnienia;
		}
		set{
			m_uprawnienia = value;
		}
	}

	public void zmienUprawniea(){

	}

}//end Ster_ZmieñUprawnienia