///////////////////////////////////////////////////////////
//  Ster_Zarz퉐zajKontem.cs
//  Implementation of the Class Ster_Zarz퉐zajKontem
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:13:41
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Zarz퉐zajKontem {

	public Ster_Zarz퉐zajKontem(){

	}

	~Ster_Zarz퉐zajKontem(){

	}

	public Dane u퓓tkownika Dane u퓓tkownika{
		get{
			return m_Dane u퓓tkownika;
		}
		set{
			m_Dane u퓓tkownika = value;
		}
	}

}//end Ster_Zarz퉐zajKontem