///////////////////////////////////////////////////////////
//  Ster_WybierzOkazje.cs
//  Implementation of the Class Ster_WybierzOkazje
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:09
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_WybierzOkazje {

	private Dane.Okazja Treœæ wybierz okazjê;

	public Ster_WybierzOkazje(){

	}

	~Ster_WybierzOkazje(){

	}

	public Okazja Okazja{
		get{
			return m_Okazja;
		}
		set{
			m_Okazja = value;
		}
	}

	public void wybierzOkazje(){

	}

}//end Ster_WybierzOkazje