///////////////////////////////////////////////////////////
//  Ster_EksportujRaport.cs
//  Implementation of the Class Ster_EksportujRaport
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:11:44
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_EksportujRaport {

	private Dane.Raport raport;

	public Ster_EksportujRaport(){

	}

	~Ster_EksportujRaport(){

	}

	public void eksportujRaport(){

	}

	public Raport Raport{
		get{
			return raport;
		}
		set{
			raport = value;
		}
	}

}//end Ster_EksportujRaport