///////////////////////////////////////////////////////////
//  WybierzTermin.cs
//  Implementation of the Class WybierzTermin
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2025 19:12:17
//  Original author: Damian Kilian
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class WybierzTermin {

	private Dane.Termin Termin;



	~WybierzTermin(){

	}

	public WybierzTermin(){

	}

	public Termin Termin{
		get{
			return Termin;
		}
		set{
			Termin = value;
		}
	}

}//end WybierzTermin