/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 06-kwi-2025 19:17:44 				*/
/*  DBMS       : MSAccess 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

ALTER TABLE [Dane] DROP CONSTRAINT [FK_Dane_Raport]

ALTER TABLE [DaneKonto u¿ytkownika] DROP CONSTRAINT [FK_DaneKonto u¿ytkownika_Konto u¿ytkownika]

ALTER TABLE [DaneKonto u¿ytkownika] DROP CONSTRAINT [FK_DaneKonto u¿ytkownika_Dane]

ALTER TABLE [DaneStatystki] DROP CONSTRAINT [FK_DaneStatystki_Statystki]

ALTER TABLE [DaneStatystki] DROP CONSTRAINT [FK_DaneStatystki_Dane]

ALTER TABLE [DaneU¿ytkownika] DROP CONSTRAINT [FK_Dane u¿ytkownika_zawiera]

ALTER TABLE [Klient] DROP CONSTRAINT [FK_Klient_KontoU¿ytkownika]

ALTER TABLE [Klient] DROP CONSTRAINT [FK_Klient_Osoba]

ALTER TABLE [KontoU¿ytkownika] DROP CONSTRAINT [FK_Konto u¿ytkownika_posiada]

ALTER TABLE [PowiadomienieRezerwacja] DROP CONSTRAINT [FK_PowiadomienieRezerwacja_Rezerwacja]

ALTER TABLE [PowiadomienieRezerwacja] DROP CONSTRAINT [FK_PowiadomienieRezerwacja_Powiadomienie]

ALTER TABLE [Pracownik] DROP CONSTRAINT [FK_Pracownik_Osoba]

ALTER TABLE [Rezerwacja] DROP CONSTRAINT [FK_Rezerwacja_Okazja]

ALTER TABLE [Rezerwacja] DROP CONSTRAINT [FK_Rezerwacja_zarz¹dza ]

ALTER TABLE [Rezerwacja] DROP CONSTRAINT [FK_Rezerwacja_Status]

ALTER TABLE [RezerwacjaTermin] DROP CONSTRAINT [FK_RezerwacjaTermin_Termin]

ALTER TABLE [RezerwacjaTermin] DROP CONSTRAINT [FK_RezerwacjaTermin_Rezerwacja]

ALTER TABLE [SalaRezerwacja] DROP CONSTRAINT [FK_SalaRezerwacja_Rezerwacja]

ALTER TABLE [SalaRezerwacja] DROP CONSTRAINT [FK_SalaRezerwacja_Sala]

ALTER TABLE [StolikSala] DROP CONSTRAINT [FK_StolikSala_Sala]

ALTER TABLE [StolikSala] DROP CONSTRAINT [FK_StolikSala_Stolik]

ALTER TABLE [Uprawnienia] DROP CONSTRAINT [FK_uprawnienia_zawiera]

ALTER TABLE [zawiera] DROP CONSTRAINT [FK_zawiera_Historia rezerwacji]

ALTER TABLE [zawiera] DROP CONSTRAINT [FK_zawiera_Konto u¿ytkownika]

/* Drop Tables */

DROP TABLE [Dane]

DROP TABLE [DaneKonto u¿ytkownika]

DROP TABLE [DaneStatystki]

DROP TABLE [DaneU¿ytkownika]

DROP TABLE [HistoriaRezerwacji]

DROP TABLE [Klient]

DROP TABLE [KontoU¿ytkownika]

DROP TABLE [Okazja]

DROP TABLE [Osoba]

DROP TABLE [Powiadomienie]

DROP TABLE [PowiadomienieRezerwacja]

DROP TABLE [Pracownik]

DROP TABLE [Raport]

DROP TABLE [Rezerwacja]

DROP TABLE [RezerwacjaTermin]

DROP TABLE [Sala]

DROP TABLE [SalaRezerwacja]

DROP TABLE [Status]

DROP TABLE [Statystki]

DROP TABLE [Stolik]

DROP TABLE [StolikSala]

DROP TABLE [Termin]

DROP TABLE [Uprawnienia]

DROP TABLE [zawiera]

/* Create Tables */

CREATE TABLE [Dane]
(
	[DaneID] varchar NOT NULL,
	[RaportID] varchar NOT NULL
)

CREATE TABLE [DaneKonto u¿ytkownika]
(
	[KontoU¿ytkownikaID] Short NULL,
	[DaneID] Short NULL
)

CREATE TABLE [DaneStatystki]
(
	[StatystkiID] Short NULL,
	[DaneID] Short NULL
)

CREATE TABLE [DaneU¿ytkownika]
(
	[DaneU¿ytkownikaID] varchar NOT NULL,
	[KontoU¿ytkownikaID] varchar NULL
)

CREATE TABLE [HistoriaRezerwacji]
(
	[HistoriaRezerwacjiID] Long NOT NULL
)

CREATE TABLE [Klient]
(
	[KlientID] Short NOT NULL,
	[KontoU¿ytkownikaID] Short NULL
)

CREATE TABLE [KontoU¿ytkownika]
(
	[Kontoid] varchar NULL,
	[KontoU¿ytkownikaID] varchar NOT NULL,
	[PracownikID] varchar NOT NULL
)

CREATE TABLE [Okazja]
(
	[RodzajOkazji] varchar NULL,
	[OkazjaID] varchar NOT NULL
)

CREATE TABLE [Osoba]
(
	[Imiê] varchar NULL,
	[Nazwisko] varchar NULL,
	[OsobaID] varchar NOT NULL
)

CREATE TABLE [Powiadomienie]
(
	[TreœæPowiadomienia] varchar NULL,
	[PowiadomienieID] varchar NOT NULL
)

CREATE TABLE [PowiadomienieRezerwacja]
(
	[RezerwacjaID] varchar NULL,
	[PowiadomienieID] varchar NULL
)

CREATE TABLE [Pracownik]
(
	[Pracownikid] varchar NULL,
	[PracownikID] varchar NOT NULL
)

CREATE TABLE [Raport]
(
	[Raportid] varchar NULL,
	[RaportID] varchar NOT NULL
)

CREATE TABLE [Rezerwacja]
(
	[RezerwacjaId] varchar NULL,
	[RezerwacjaID] varchar NOT NULL,
	[OkazjaID] varchar NULL,
	[KlientID] Short NOT NULL,
	[StatusID] varchar NOT NULL
)

CREATE TABLE [RezerwacjaTermin]
(
	[TerminID] varchar NULL,
	[RezerwacjaID] varchar NULL
)

CREATE TABLE [Sala]
(
	[IloœæStolików] varchar NULL,
	[Salaid] varchar NULL,
	[SalaID] varchar NOT NULL
)

CREATE TABLE [SalaRezerwacja]
(
	[RezerwacjaID] varchar NULL,
	[SalaID] varchar NULL
)

CREATE TABLE [Status]
(
	[Statusrezerwacji] varchar NULL,
	[StatusID] varchar NOT NULL
)

CREATE TABLE [Statystki]
(
	[Statystyki] varchar NULL,
	[StatystkiID] varchar NOT NULL
)

CREATE TABLE [Stolik]
(
	[IloœæMiejsc] varchar NULL,
	[Stolikid] varchar NULL,
	[StolikID] varchar NOT NULL
)

CREATE TABLE [StolikSala]
(
	[SalaID] varchar NULL,
	[StolikID] varchar NULL
)

CREATE TABLE [Termin]
(
	[Data] varchar NULL,
	[TerminID] varchar NOT NULL
)

CREATE TABLE [Uprawnienia]
(
	[Uprawnieniaid] varchar NULL,
	[UprawnieniaID] varchar NOT NULL,
	[KontoU¿ytkownikaID] varchar NULL
)

CREATE TABLE [zawiera]
(
	[HistoriaRezerwacjiID] Long NULL,
	[KontoU¿ytkownikaID] varchar NULL
)

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Dane] ADD CONSTRAINT [PK_Dane]
	PRIMARY KEY ([DaneID])

ALTER TABLE [DaneU¿ytkownika] ADD CONSTRAINT [PK_DaneU¿ytkownika]
	PRIMARY KEY ([DaneU¿ytkownikaID])

ALTER TABLE [HistoriaRezerwacji] ADD CONSTRAINT [PK_HistoriaRezerwacji]
	PRIMARY KEY ([HistoriaRezerwacjiID])

ALTER TABLE [Klient] ADD CONSTRAINT [PK_Klient]
	PRIMARY KEY ([KlientID])

ALTER TABLE [KontoU¿ytkownika] ADD CONSTRAINT [PK_KontoU¿ytkownika]
	PRIMARY KEY ([KontoU¿ytkownikaID])

ALTER TABLE [Okazja] ADD CONSTRAINT [PK_Okazja]
	PRIMARY KEY ([OkazjaID])

ALTER TABLE [Osoba] ADD CONSTRAINT [PK_Osoba]
	PRIMARY KEY ([OsobaID])

ALTER TABLE [Powiadomienie] ADD CONSTRAINT [PK_Powiadomienie]
	PRIMARY KEY ([PowiadomienieID])

ALTER TABLE [Pracownik] ADD CONSTRAINT [PK_Pracownik]
	PRIMARY KEY ([PracownikID])

ALTER TABLE [Raport] ADD CONSTRAINT [PK_Raport]
	PRIMARY KEY ([RaportID])

ALTER TABLE [Rezerwacja] ADD CONSTRAINT [PK_Rezerwacja]
	PRIMARY KEY ([RezerwacjaID])

ALTER TABLE [Sala] ADD CONSTRAINT [PK_Sala]
	PRIMARY KEY ([SalaID])

ALTER TABLE [Status] ADD CONSTRAINT [PK_Status]
	PRIMARY KEY ([StatusID])

ALTER TABLE [Statystki] ADD CONSTRAINT [PK_Statystki]
	PRIMARY KEY ([StatystkiID])

ALTER TABLE [Stolik] ADD CONSTRAINT [PK_Stolik]
	PRIMARY KEY ([StolikID])

ALTER TABLE [Termin] ADD CONSTRAINT [PK_Termin]
	PRIMARY KEY ([TerminID])

ALTER TABLE [Uprawnienia] ADD CONSTRAINT [PK_Uprawnienia]
	PRIMARY KEY ([UprawnieniaID])

/* Create Foreign Key Constraints */

ALTER TABLE [Dane] ADD CONSTRAINT [FK_Dane_Raport]
	FOREIGN KEY ([RaportID]) REFERENCES [Raport] ([RaportID])

ALTER TABLE [DaneKonto u¿ytkownika] ADD CONSTRAINT [FK_DaneKonto u¿ytkownika_Konto u¿ytkownika]
	FOREIGN KEY ([KontoU¿ytkownikaID]) REFERENCES [KontoU¿ytkownika] ([KontoU¿ytkownikaID])

ALTER TABLE [DaneKonto u¿ytkownika] ADD CONSTRAINT [FK_DaneKonto u¿ytkownika_Dane]
	FOREIGN KEY ([DaneID]) REFERENCES [Dane] ([DaneID])

ALTER TABLE [DaneStatystki] ADD CONSTRAINT [FK_DaneStatystki_Statystki]
	FOREIGN KEY ([StatystkiID]) REFERENCES [Statystki] ([StatystkiID])

ALTER TABLE [DaneStatystki] ADD CONSTRAINT [FK_DaneStatystki_Dane]
	FOREIGN KEY ([DaneID]) REFERENCES [Dane] ([DaneID])

ALTER TABLE [DaneU¿ytkownika] ADD CONSTRAINT [FK_Dane u¿ytkownika_zawiera]
	FOREIGN KEY ([KontoU¿ytkownikaID]) REFERENCES [KontoU¿ytkownika] ([KontoU¿ytkownikaID])

ALTER TABLE [Klient] ADD CONSTRAINT [FK_Klient_KontoU¿ytkownika]
	FOREIGN KEY ([KontoU¿ytkownikaID]) REFERENCES [KontoU¿ytkownika] ([KontoU¿ytkownikaID])

ALTER TABLE [Klient] ADD CONSTRAINT [FK_Klient_Osoba]
	FOREIGN KEY ([KlientID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [KontoU¿ytkownika] ADD CONSTRAINT [FK_Konto u¿ytkownika_posiada]
	FOREIGN KEY ([PracownikID]) REFERENCES [Pracownik] ([PracownikID])

ALTER TABLE [PowiadomienieRezerwacja] ADD CONSTRAINT [FK_PowiadomienieRezerwacja_Rezerwacja]
	FOREIGN KEY ([RezerwacjaID]) REFERENCES [Rezerwacja] ([RezerwacjaID])

ALTER TABLE [PowiadomienieRezerwacja] ADD CONSTRAINT [FK_PowiadomienieRezerwacja_Powiadomienie]
	FOREIGN KEY ([PowiadomienieID]) REFERENCES [Powiadomienie] ([PowiadomienieID])

ALTER TABLE [Pracownik] ADD CONSTRAINT [FK_Pracownik_Osoba]
	FOREIGN KEY ([PracownikID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Rezerwacja] ADD CONSTRAINT [FK_Rezerwacja_Okazja]
	FOREIGN KEY ([OkazjaID]) REFERENCES [Okazja] ([OkazjaID])

ALTER TABLE [Rezerwacja] ADD CONSTRAINT [FK_Rezerwacja_zarz¹dza ]
	FOREIGN KEY ([KlientID]) REFERENCES [Klient] ([KlientID])

ALTER TABLE [Rezerwacja] ADD CONSTRAINT [FK_Rezerwacja_Status]
	FOREIGN KEY ([StatusID]) REFERENCES [Status] ([StatusID])

ALTER TABLE [RezerwacjaTermin] ADD CONSTRAINT [FK_RezerwacjaTermin_Termin]
	FOREIGN KEY ([TerminID]) REFERENCES [Termin] ([TerminID])

ALTER TABLE [RezerwacjaTermin] ADD CONSTRAINT [FK_RezerwacjaTermin_Rezerwacja]
	FOREIGN KEY ([RezerwacjaID]) REFERENCES [Rezerwacja] ([RezerwacjaID])

ALTER TABLE [SalaRezerwacja] ADD CONSTRAINT [FK_SalaRezerwacja_Rezerwacja]
	FOREIGN KEY ([RezerwacjaID]) REFERENCES [Rezerwacja] ([RezerwacjaID])

ALTER TABLE [SalaRezerwacja] ADD CONSTRAINT [FK_SalaRezerwacja_Sala]
	FOREIGN KEY ([SalaID]) REFERENCES [Sala] ([SalaID])

ALTER TABLE [StolikSala] ADD CONSTRAINT [FK_StolikSala_Sala]
	FOREIGN KEY ([SalaID]) REFERENCES [Sala] ([SalaID])

ALTER TABLE [StolikSala] ADD CONSTRAINT [FK_StolikSala_Stolik]
	FOREIGN KEY ([StolikID]) REFERENCES [Stolik] ([StolikID])

ALTER TABLE [Uprawnienia] ADD CONSTRAINT [FK_uprawnienia_zawiera]
	FOREIGN KEY ([KontoU¿ytkownikaID]) REFERENCES [KontoU¿ytkownika] ([KontoU¿ytkownikaID])

ALTER TABLE [zawiera] ADD CONSTRAINT [FK_zawiera_Historia rezerwacji]
	FOREIGN KEY ([HistoriaRezerwacjiID]) REFERENCES [HistoriaRezerwacji] ([HistoriaRezerwacjiID])

ALTER TABLE [zawiera] ADD CONSTRAINT [FK_zawiera_Konto u¿ytkownika]
	FOREIGN KEY ([KontoU¿ytkownikaID]) REFERENCES [KontoU¿ytkownika] ([KontoU¿ytkownikaID])
